### ISSUE TITLE
Keep track of whether ProjectConsent relates to an Entitlement that is active in REMS

### ISSUE THREAD

**Issue by yuriy-pavlov** [dycons/consents#7]
Add a field representing whether the project associated with a resource's `consent` metadata is actively Entitled to access that resource, according to REMS. If the value is false, the resource should *not* be returned as a query result even if the consent allows for it, because the REMS Entitlement has been revoked.

`EntitlementIsActive` should be automatically set to `true` when the REMS `add entitlement` webhook is ingested at the `/rems/add_entitlement` endpoint.

`EntitlementIsActive` should automatically be set to `false` when REMS informs the consents service that an entitlement has been removed, at the `rems/remove_entitlement` endpoint. However, the REMS `remove entitlement` webhook currently pushes every time any individual user has an Entitlement removed, and the consents service is only interested in Entitlements as they pertain to entire data access Applications. Therefore, the current `remove entitlement` webhook is not an appropriate cue for setting `EntitlementIsActive` to false.

### Schemas

**Data model:** Add column `EntitlementIsActive : bool` to ProjectConsent table, representing whether this project's data access Entitlement is active in REMS.

**API entity:** Add property `entitlement_is_active` to ProjectConsent entity, representing whether this project's data access Entitlement is active in REMS. Swagger schema:
```
entitlement_is_active:
        type: boolean
        description: (T/F)- This project's data access Entitlement is active in REMS
        example: false
        readOnly: true
```
